// automatically generated by wsjcpp:v0.1.0

#include "__data__gitignore_pathe282c3.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data__gitignore_pathe282c3)

const std::string &RES___data__gitignore_pathe282c3::getFilename() const {
  static const std::string s = "./data/.gitignore";
  return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data__gitignore_pathe282c3::getPackAs() const {
  static const std::string s = "text";
  return s;
}
// ---------------------------------------------------------------------

int RES___data__gitignore_pathe282c3::getBufferSize() const {
  return 47;
}

// ---------------------------------------------------------------------

const char *RES___data__gitignore_pathe282c3::getBuffer() const {
  static const std::string sRet = "" // size: 47
    "/web-sites\n"
    "/repositories\n"
    "!config.yml\n"
    "!/config.d"
  ;
  return sRet.c_str();
} //::getBuffer()
