// automatically generated by wsjcpp:v0.2.8

#include <wsjcpp_core.h>

class RES___data_html_admin_js_bootstrap_esm_min_js_map_path92bf0f : public WsjcppResourceFile {
public:
  virtual const std::string &getFilename() const override;
  virtual const std::string &getPackAs() const override;
  virtual int getBufferSize() const override;
  virtual const char *getBuffer() const override;
};
