// automatically generated by wsjcpp:v0.2.8

#include <wsjcpp_core.h>

class RES___data_html_control_panel_js_bootstrap_bundle_min_js_path183f41 : public WsjcppResourceFile {
public:
  virtual const std::string &getFilename() const override;
  virtual const std::string &getPackAs() const override;
  virtual int getBufferSize() const override;
  virtual const char *getBuffer() const override;
};
