// automatically generated by wsjcpp:v0.2.8

#include <wsjcpp_core.h>

class RES___data_html_admin_css_bootstrap_utilities_rtl_min_css_path196a6e : public WsjcppResourceFile {
public:
  virtual const std::string &getFilename() const override;
  virtual const std::string &getPackAs() const override;
  virtual int getBufferSize() const override;
  virtual const char *getBuffer() const override;
};
