// automatically generated by wsjcpp:v0.1.0

#include "__data_config_yml_path8aca03.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_config_yml_path8aca03)

const std::string &RES___data_config_yml_path8aca03::getFilename() const {
  static const std::string s = "./data/config.yml";
  return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_config_yml_path8aca03::getPackAs() const {
  static const std::string s = "text";
  return s;
}
// ---------------------------------------------------------------------

int RES___data_config_yml_path8aca03::getBufferSize() const {
  return 723;
}

// ---------------------------------------------------------------------

const char *RES___data_config_yml_path8aca03::getBuffer() const {
  static const std::string sRet = "" // size: 723
    "\n"
    "port: 10233\n"
    "\n"
    "repositories:\n"
    "  repo-sea5kg-ru:\n"
    "    type: git\n"
    "    url: https://github.com/sea5kg/sea5kg_ru\n"
    "    webhook-update: r6zyNcCTAw\n"
    "  repo-pipeline-editor-s5:\n"
    "    type: git\n"
    "    url: https://github.com/sea5kg/pipeline-editor-s5\n"
    "    webhook-update: cNt20Tm0zU\n"
    "  repo-wsjcpp-org:\n"
    "    type: git\n"
    "    url: https://github.com/wsjcpp/wsjcpp-org\n"
    "    webhook-update: tgNi7sZiQV\n"
    "\n"
    "mapping-host-and-path-folders:\n"
    "  \"sea5kg.ru\": \"${repo-sea5kg-ru}/html\"\n"
    "  \"localhost/sea5kg_ru\": \"${repo-sea5kg-ru}/html\"\n"
    "  \"sea5kg.ru/pipeline-editor-s5\": \"${repo-pipeline-editor-s5}/html\"\n"
    "  \"localhost/pipeline-editor-s5\": \"${repo-pipeline-editor-s5}/html\"\n"
    "  \"wsjcpp.org\": \"${repo-wsjcpp-org}/web\"\n"
    "  \"localhost/wsjcpp_org/\": \"${repo-wsjcpp-org}/web\"\n"
    ""
  ;
  return sRet.c_str();
} //::getBuffer()
