// automatically generated by wsjcpp:v0.1.0

#include "__data_html_admin_js_index_js_path091b1e.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_html_admin_js_index_js_path091b1e)

const std::string &RES___data_html_admin_js_index_js_path091b1e::getFilename() const {
  static const std::string s = "./data/html/admin/js/index.js";
  return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_html_admin_js_index_js_path091b1e::getPackAs() const {
  static const std::string s = "text";
  return s;
}
// ---------------------------------------------------------------------

int RES___data_html_admin_js_index_js_path091b1e::getBufferSize() const {
  return 949;
}

// ---------------------------------------------------------------------

const char *RES___data_html_admin_js_index_js_path091b1e::getBuffer() const {
  static const std::string sRet = "" // size: 949
    "\n"
    "function test_api() {\n"
    "      $.ajax({\n"
    "        url: \"/api\", // Server endpoint URL\n"
    "        method: \"POST\",            // HTTP method (GET, POST, PUT, DELETE, etc.)\n"
    "        dataType: \"json\",          // Expected data type in the response (xml, json, script, html)\n"
    "        contentType: \"application/json\",\n"
    "        data: JSON.stringify({\n"
    "            method: \"John\",\n"
    "            location: \"Boston\"\n"
    "        }),\n"
    "        success: function(data) {  // Function to run if the request succeeds\n"
    "            console.log(\"Data received:\", data);\n"
    "            // Process the data here (e.g., update UI)\n"
    "        },\n"
    "        error: function(jqXHR, textStatus, errorThrown) { // Function to run if an error occurs\n"
    "            alert(\"Error: \" + textStatus + \" : \" + errorThrown);\n"
    "        },\n"
    "        complete: function(jqXHR, status) { // Function to run when the request finishes (after success or error)\n"
    "            console.log(\"Request finished.\");\n"
    "        }\n"
    "    });\n"
    "}"
  ;
  return sRet.c_str();
} //::getBuffer()
