// automatically generated by wsjcpp:v0.1.0

#include "__data_html_index_html_pathffd2bc.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_html_index_html_pathffd2bc)

const std::string &RES___data_html_index_html_pathffd2bc::getFilename() const {
  static const std::string s = "./data/html/index.html";
  return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_html_index_html_pathffd2bc::getPackAs() const {
  static const std::string s = "text";
  return s;
}
// ---------------------------------------------------------------------

int RES___data_html_index_html_pathffd2bc::getBufferSize() const {
  return 73;
}

// ---------------------------------------------------------------------

const char *RES___data_html_index_html_pathffd2bc::getBuffer() const {
  static const std::string sRet = "" // size: 73
    "<html>\n"
    "<head>\n"
    "</head>\n"
    "<body>\n"
    "Welcome to my-little-dev-lab\n"
    "</body>\n"
    "</html>"
  ;
  return sRet.c_str();
} //::getBuffer()
