// automatically generated by wsjcpp:v0.2.8

#include <wsjcpp_core.h>

class RES___data_html_control_panel_css_bootstrap_rtl_min_css_map_pathb5cd2f : public WsjcppResourceFile {
public:
  virtual const std::string &getFilename() const override;
  virtual const std::string &getPackAs() const override;
  virtual int getBufferSize() const override;
  virtual const char *getBuffer() const override;
};
