// automatically generated by wsjcpp:v0.1.0

#include "__data_html_control_panel_index_html_path1c09a9.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_html_control_panel_index_html_path1c09a9)

const std::string &RES___data_html_control_panel_index_html_path1c09a9::getFilename() const {
  static const std::string s = "./data/html/control-panel/index.html";
  return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_html_control_panel_index_html_path1c09a9::getPackAs() const {
  static const std::string s = "text";
  return s;
}
// ---------------------------------------------------------------------

int RES___data_html_control_panel_index_html_path1c09a9::getBufferSize() const {
  return 2905;
}

// ---------------------------------------------------------------------

const char *RES___data_html_control_panel_index_html_path1c09a9::getBuffer() const {
  static const std::string sRet = "" // size: 2905
    "<!doctype html>\n"
    "<html>\n"
    "<head>\n"
    "  <title>My-Little-Dev-Lab (Control-Panel)</title>\n"
    "  <meta charset=\"utf-8\"/>\n"
    "  <meta name=\"Keywords\" content=\"my-little-dev-lab\"/>\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <meta name=\"description\" content=\"my-little-dev-lab\">\n"
    "  <link rel=\"shortcut icon\" href=\"favicon.ico\">\n"
    "\n"
    "  <link href='css/bootstrap.min.css' rel='stylesheet' type='text/css'/>\n"
    "  <script type=\"text/javascript\" src=\"./js/jquery-3.7.1.js\"></script>\n"
    "  <script type=\"text/javascript\" src=\"./js/popper.min.js\"></script>\n"
    "  <script type=\"text/javascript\" src=\"./js/tooltip.min.js\"></script>\n"
    "  <script type=\"text/javascript\" src=\"./js/bootstrap.min.js\"></script>\n"
    "  <script type=\"text/javascript\" src=\"./js/index.js\"></script>\n"
    "</head>\n"
    "<body>\n"
    "  <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n"
    "  <div class=\"container-fluid\">\n"
    "    <a class=\"navbar-brand\" href=\"#\">My-Little-Dev-Lab (Control-Panel)</a>\n"
    "    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
    "      <span class=\"navbar-toggler-icon\"></span>\n"
    "    </button>\n"
    "    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
    "      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n"
    "        <li class=\"nav-item\">\n"
    "          <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Home</a>\n"
    "        </li>\n"
    "        <li class=\"nav-item\">\n"
    "          <a class=\"nav-link\" onclick=\"test_api()\">Link</a>\n"
    "        </li>\n"
    "        <li class=\"nav-item dropdown\">\n"
    "          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n"
    "            Dropdown\n"
    "          </a>\n"
    "          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n"
    "            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\n"
    "            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\n"
    "            <li><hr class=\"dropdown-divider\"></li>\n"
    "            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\n"
    "          </ul>\n"
    "        </li>\n"
    "        <li class=\"nav-item\">\n"
    "          <a class=\"nav-link disabled\" href=\"#\" tabindex=\"-1\" aria-disabled=\"true\">Disabled</a>\n"
    "        </li>\n"
    "      </ul>\n"
    "      <form class=\"d-flex\">\n"
    "        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n"
    "        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\n"
    "      </form>\n"
    "    </div>\n"
    "  </div>\n"
    "</nav>\n"
    "\n"
    "<div class=\"container\">\n"
    "  Hello world! 111\n"
    "  <div class=\"card\" style=\"width: 18rem;\">\n"
    "    <img src=\"...\" class=\"card-img-top\" alt=\"...\">\n"
    "    <div class=\"card-body\">\n"
    "      <h5 class=\"card-title\">Test API</h5>\n"
    "      <p class=\"card-text\">Example API call ajax</p>\n"
    "      <a href=\"#\" class=\"btn btn-primary\" onclick=\"test_api()\">Run</a>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "</body>\n"
    "</html>"
  ;
  return sRet.c_str();
} //::getBuffer()
