// automatically generated by wsjcpp:v0.2.8

#include <wsjcpp_core.h>

class RES___data_config_yml_path8aca03 : public WsjcppResourceFile {
public:
  virtual const std::string &getFilename() const override;
  virtual const std::string &getPackAs() const override;
  virtual int getBufferSize() const override;
  virtual const char *getBuffer() const override;
};
